version: 2.1

jobs:
  build:
    docker:
      # use the same image in which the build will run
      - image: circleci/python:3.8-buster

    steps:
      - checkout

      # install Docker and Docker Compose
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      # build and push Docker image
      - run:
          name: Build and push Docker image
          command: |
            docker pull vital987/code-server

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          # only run the job on the master branch
          filters:
            branches:
              only:
                - master